AWSTemplateFormatVersion: '2010-09-09'
Description: 'SNS Topic'
Parameters:
  SubscriptionEndPoint:
    Type: String
  SubscriptionProtocol:
    Type: String
    AllowedValues:
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: Ref


