AWSTemplateFormatVersion: '2010-09-09'
Description: 'SQS Standard Queue sample'
Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: standard-queue
      DelaySeconds: 5
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 5
